
spring.application.name=order-api

spring.datasource.url=jdbc:postgresql://localhost:1111/postgres
spring.datasource.username=postgres
spring.datasource.password=Hira11s2.

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.flywaydb=DEBUG